AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
Resources:
  MySampleBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/sample
      Handler: index.slackHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          SLACK_BOT_TOKEN: Token
      Events:
        hook:
          Type: Api
          Properties:
            Path: /hook
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
