AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
Resources:
  MySampleBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/sample
      Handler: slackHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5000
      Environment:
        Variables:
      Events:
        hook:
          Type: Api
          Properties:
            Path: /hook
            Method: POST
